apiVersion: batch/v1
kind: CronJob
metadata:
  name: node-metrics-cronjob
spec:
  schedule: "*/1 * * * *"  # Run every minute (configurable)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: metrics-container
            image: rahulbhatia1998/node-exporter-linux-1
            volumeMounts:
            - name: data-volume
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: data-pvc
